version: "3.3"
services:
  mysql-for-wechat:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_USER: 'sergey'
      MYSQL_PASSWORD: 'sergey'
      MYSQL_ROOT_PASSWORD: 'sergey'
      MYSQL_DATABASE: 'wechat'
    volumes:
      - /home/mysql/data:/var/lib/mysql
    container_name:
      mysql
  wechat:
    build: .
    restart: always
    container_name: wechat_server
    depends_on:
      - mysql
    volumes:
      - /home/ccloud/wechat/config.json:/usr/app/config.json
    ports:
      - "8096:8096"
    command:
      - "--config /usr/app/config.json"