version: "3.8"
services:
  mysql:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_USER: 'sergey'
      MYSQL_PASSWORD: 'sergey'
      MYSQL_ROOT_PASSWORD: 'sergey'
    volumes:
      - /home/mysql/data:/var/lib/mysql
    container_name:
      mysql-for-wechat
